name: arona_assistant
description: 一個語音對話的アロナ助手
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  flutter_tts: ^3.6.3
  speech_to_text: ^6.3.0

flutter:
  uses-material-design: true
